
--------------------------------------------------------------
-- Database table removal script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- note: spaces within table names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- Use this script to drop the tables created by -
--   'C:\Users\acer\Desktop\db_schema.sql'

-- Dropping a table has the effect of removing it from the Database.  All existing data is lost
-- as well as the definition of the table itself (stored as meta-data).  Dropping the tables allows
-- them to be re-created within the Database, even if they already exist.


--------------------------------------------------------------

-- Drop tables --

DROP TABLE COUPON_ORDER;

DROP TABLE REVIEWS;

DROP TABLE PRODUCT;

DROP TABLE PAYMENT;

DROP TABLE ORDER_ITEM;

DROP TABLE ORDER;

DROP TABLE USER;

DROP TABLE DISCOUNT;

DROP TABLE CART_PRODUCT;

DROP TABLE SHOP;

DROP TABLE COLLECTION_SLOT;

DROP TABLE REPORT;

DROP TABLE CART;

DROP TABLE PRODUCT_REPORT;

DROP TABLE WISHLIST;

DROP TABLE WISHLIST_PRODUCT;

DROP TABLE COUPON;


--------------------------------------------------------------
-- End of DDL DROP file auto-generation
--------------------------------------------------------------
